development:
  adapter: async
  # adapter: redis

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:db2287bd767c06bb3cfab474ff6a6e71@scat.redistogo.com:10581/
  # channel_prefix: plivo_api_production
